engines/teaser/config/routes.rb
Teaser::Engine.routes.draw do
  root to: 'pre_registrants#new'
  resources :pre_registrants
end

engines/teaser/app/models/teaser/application_record.rb
module Teaser
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/teaser/app/models/teaser/pre_registrant.rb
module Teaser
  class PreRegistrant < ApplicationRecord
  end
end

engines/teaser/app/controllers/teaser/application_controller.rb
module Teaser
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

engines/teaser/app/controllers/teaser/pre_registrants_controller.rb
require_dependency "teaser/application_controller"

module Teaser
  class PreRegistrantsController < ApplicationController
    before_action :set_pre_registrant, only: [:show, :edit, :update, :destroy]

    # GET /pre_registrants
    def index
      @pre_registrants = PreRegistrant.all
    end

    # GET /pre_registrants/1
    def show
    end

    # GET /pre_registrants/new
    def new
      @pre_registrant = PreRegistrant.new
    end

    # GET /pre_registrants/1/edit
    def edit
    end

    # POST /pre_registrants
    def create
      @pre_registrant = PreRegistrant.new(pre_registrant_params)

      if @pre_registrant.save
        redirect_to @pre_registrant, notice: 'Pre registrant was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /pre_registrants/1
    def update
      if @pre_registrant.update(pre_registrant_params)
        redirect_to @pre_registrant, notice: 'Pre registrant was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /pre_registrants/1
    def destroy
      @pre_registrant.destroy
      redirect_to pre_registrants_url, notice: 'Pre registrant was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_pre_registrant
        @pre_registrant = PreRegistrant.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def pre_registrant_params
        params.require(:pre_registrant).permit(:name, :email)
      end
  end
end

engines/teaser/app/helpers/teaser/application_helper.rb
module Teaser
  module ApplicationHelper
  end
end

engines/teaser/app/helpers/teaser/pre_registrants_helper.rb
module Teaser
  module PreRegistrantsHelper
  end
end

engines/teaser/app/views/layouts/teaser/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teaser</title>
  <%= stylesheet_link_tag    "teaser/application", media: "all" %>
  <%= javascript_include_tag "teaser/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

engines/teaser/app/views/teaser/pre_registrants/_form.html.erb
<%= form_for(pre_registrant) do |f| %>
  <% if pre_registrant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pre_registrant.errors.count, "error") %> prohibited this pre_registrant from being saved:</h2>

      <ul>
      <% pre_registrant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

engines/teaser/app/views/teaser/pre_registrants/edit.html.erb
<h1>Editing Pre Registrant</h1>

<%= render 'form', pre_registrant: @pre_registrant %>

<%= link_to 'Show', @pre_registrant %> |
<%= link_to 'Back', pre_registrants_path %>

engines/teaser/app/views/teaser/pre_registrants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pre Registrants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pre_registrants.each do |pre_registrant| %>
      <tr>
        <td><%= pre_registrant.name %></td>
        <td><%= pre_registrant.email %></td>
        <td><%= link_to 'Show', pre_registrant %></td>
        <td><%= link_to 'Edit', edit_pre_registrant_path(pre_registrant) %></td>
        <td><%= link_to 'Destroy', pre_registrant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pre Registrant', new_pre_registrant_path %>

engines/teaser/app/views/teaser/pre_registrants/new.html.erb
<h1>New Pre Registrant</h1>

<%= render 'form', pre_registrant: @pre_registrant %>

<%= link_to 'Back', pre_registrants_path %>

engines/teaser/app/views/teaser/pre_registrants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pre_registrant.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pre_registrant.email %>
</p>

<%= link_to 'Edit', edit_pre_registrant_path(@pre_registrant) %> |
<%= link_to 'Back', pre_registrants_path %>